29/effects refactoring
Margi47/Crm pull request #30
Opened 2017-05-02 14:46 UTC by Margi47

2017-05-02 21:15 UTC, zihotki requested changes

2017-05-02 21:15 UTC, zihotki commented on ClientApp/app/services/group.service.ts
> +                    this.addTeachers(g.id, group.teachers.map(t => t.id)).subscribe();
This is wrong, we need to return an obserbable instead of subscribing

2017-05-02 21:15 UTC, zihotki commented on ClientApp/app/services/teacher.service.ts
> +                    this.addGroups(teacher.id, teacher.groups.map(g => g.id)).subscribe();
This is wrong, we need to return an obserbable instead of subscribing

2017-05-02 21:15 UTC, zihotki commented on ClientApp/app/services/user.service.ts
> +                    this.createTeacher(user).subscribe();
This is wrong, we need to return an obserbable instead of subscribing

2017-05-03 09:43 UTC, Margi47 commented
Requested changes have been applied in last commit

2017-05-03 22:09 UTC, zihotki approved these changes

2017-05-04 18:52 UTC, merged