GroupTeacherRepository and Controller added
Margi47/Crm pull request #31
Opened 2017-05-02 17:02 UTC by Margi47

2017-05-02 21:01 UTC, zihotki requested changes

2017-05-02 21:01 UTC, zihotki commented on Repositories/GroupTeacherRepository.cs
> +                           .Select(g => g.Teacher)
We can directly select user info `g.Teacher.User`

2017-05-02 21:01 UTC, zihotki commented on Repositories/GroupTeacherRepository.cs
> +            var entity = _context.GroupTeachers.First(g => g.GroupId == groupId && g.TeacherId == teacherId);
`First` guarantees that there always will be either result or an exception. It should be either FirstOrDefault or null check at line 71 should be removed

2017-05-03 09:42 UTC, Margi47 commented
Requested changes have been applied in last commit

2017-05-03 22:09 UTC, zihotki approved these changes

2017-05-03 22:10 UTC, merged